version: '3'

services:
  app:
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data:rw
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Optional: Add a reverse proxy like Nginx for SSL termination
  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - app 